- name: Check if Semaphore secret is available
  hosts: all
  vars:
    docker_user_ssh_pubkey: "{{ lookup('env','DOCKER_USER_SSH_PUBKEY') }}"
  tasks:
    - name: Debug SSH key
      debug:
        msg: "{{ docker_user_ssh_pubkey }}"
